field: 29f9f687-2186-4ee6-8d1e-b18913c70fb0 # Recipe Content
fieldLayouts:
  9565b65b-42ad-4de3-ab59-2c5c447f5f01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6ddb394f-6aa1-4af1-a23d-4a540295101f # Tip
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e73c95c3-c720-496c-9e25-a77e90c9a3d9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e00409e6-f6b5-4628-a73d-927df32d3a6a
        userCondition: null
fields:
  6ddb394f-6aa1-4af1-a23d-4a540295101f: # Tip
    columnSuffix: rjllflcq
    contentColumnType: text
    fieldGroup: null
    handle: tip
    instructions: null
    name: Tip
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipesTip
name: 'Recipes Tip'
sortOrder: 2
