fieldLayouts:
  355ed4c4-81aa-4486-aacb-f43efb67fe3a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0909d6fa-df27-4f32-9626-8dbdde285479 # Drink Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf7caa3a-bb83-454a-b91d-a04fa624fe3a
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Drinks Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7375ccbc-ee50-42b5-9304-e93bf011953c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dac6ec54-e8fd-4fd5-a70e-4ef5b7be4beb # Drinks Recipe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a864ac0e-a39d-4970-b66c-2b27a4339c07
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c8abab5-2943-4c23-82c1-5e0b4e7c0a15 # Drinks Subname
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 323fa020-fbd2-43fa-b611-950c4e440c23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: caf72bd8-9047-43e6-bd51-44e0c9a961ae # Drinks Introduction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f35069b6-954a-4a7b-a600-83286a80331d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2f63b7b4-5e72-4d8d-8827-39c2c4f60770 # Drinks Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a373d6a1-e377-4f3a-a8b7-e56141c16408
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 251b212e-1c35-439c-bfc2-062a5c0906d1 # Drinks Page Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6724b79-decc-4651-a848-1ca19e7fce6c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 415778a4-716e-4b2c-9c80-7588a76100d9 # Drinks Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 887f2f29-fc05-454d-9a55-5863b2cc4518
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 966a26b3-8f00-4f50-9de2-2047a0514ca2 # Drinks Date Added
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10c67bf3-8f47-4c10-a30d-49564b25fa47
            userCondition: null
            warning: null
            width: 100
        name: Drinks
        uid: cfcbc2bb-b773-4425-8211-f72259394a0d
        userCondition: null
handle: drinks
hasTitleField: true
name: Drinks
section: b3a35b86-a2bc-4529-b334-7895bfdfd9bc # Drinks
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
