columnSuffix: hsixpzlg
contentColumnType: text
fieldGroup: 1b146738-91b7-4f8c-8a60-a133456ab1e8 # About
handle: aboutIntroduction
instructions: 'Short sentence at top of about page'
name: 'About Introduction'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
