columnSuffix: dpsdvlhj
contentColumnType: text
fieldGroup: 8411ea9e-6c77-4fff-a6c6-bf950dd522f6 # Drinks
handle: drinksImageCaption
instructions: 'Insert an image caption for the drink here'
name: 'Drinks Image Caption'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
