columnSuffix: zhwotryi
contentColumnType: text
fieldGroup: 7a6521b4-eecf-4ad8-864c-697565f96323 # Home
handle: homePageCopy
instructions: 'Insert page copy into home page'
name: 'Home Page Copy'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: null
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
