defaultPlacement: end
enableVersioning: true
handle: drinksHome
name: 'Drinks Home'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  037296d6-cae9-410a-9f08-b0b09fc4dd7a: # Crafty Coffee
    enabledByDefault: true
    hasUrls: true
    template: drinks/_entry.twig
    uriFormat: drinks-home
type: single
