defaultPlacement: end
enableVersioning: true
handle: recipes
name: Recipes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - 'http://craftycoffee.test/'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  037296d6-cae9-410a-9f08-b0b09fc4dd7a: # Crafty Coffee
    enabledByDefault: true
    hasUrls: true
    template: recipes/_entry
    uriFormat: 'recipes/{slug}'
type: channel
